def pollrho(n, k, seed):
    """
    Performs Pollard's Rho Factorization Algorithm up to k times.
    Indicates when a repeat congruence is discovered, at which indices, and how far apart they are (range).

    This is meant to be a demonstration of the periodicity of the sequence of factors of n generated by the recurrence.

    n: number to factorize
    k: iterations of recurrence
    seed: initial x value
    """
    x_k = seed
    sequence = {x_k: 0}
    
    for j in range(k):
        # Recurrence relation
        x_k_1 = (x_k**2 + 1) % n

        output = f"x^{j:<2} = {x_k_1:<7} (mod {n})"

        # Check for repeats
        if x_k_1 in sequence:
            i = sequence[x_k_1]
            output += f"    Found Repeat: {x_k_1:>4} at i = {i:>2} and j = {j:>2}. Range: {j-i}"
        
        # Update sequence
        sequence[x_k_1] = j

        # Update x_k for next recurrence
        x_k = x_k_1

        print(output)

# Example from Exercise 4.30 in the book
pollrho(8051, 70, 2)

# Output
"""
x^0  = 5       (mod 8051)
x^1  = 26      (mod 8051)
x^2  = 677     (mod 8051)
x^3  = 7474    (mod 8051)
x^4  = 2839    (mod 8051)
x^5  = 871     (mod 8051)
x^6  = 1848    (mod 8051)
x^7  = 1481    (mod 8051)
x^8  = 3490    (mod 8051)
x^9  = 6989    (mod 8051)
x^10 = 705     (mod 8051)
x^11 = 5915    (mod 8051)
x^12 = 5631    (mod 8051)
x^13 = 3324    (mod 8051)
x^14 = 3005    (mod 8051)
x^15 = 4855    (mod 8051)
x^16 = 5749    (mod 8051)
x^17 = 1647    (mod 8051)
x^18 = 7474    (mod 8051)    Found Repeat: 7474 at i =  3 and j = 18. Range: 15
x^19 = 2839    (mod 8051)    Found Repeat: 2839 at i =  4 and j = 19. Range: 15
x^20 = 871     (mod 8051)    Found Repeat:  871 at i =  5 and j = 20. Range: 15
x^21 = 1848    (mod 8051)    Found Repeat: 1848 at i =  6 and j = 21. Range: 15
x^22 = 1481    (mod 8051)    Found Repeat: 1481 at i =  7 and j = 22. Range: 15
x^23 = 3490    (mod 8051)    Found Repeat: 3490 at i =  8 and j = 23. Range: 15
x^24 = 6989    (mod 8051)    Found Repeat: 6989 at i =  9 and j = 24. Range: 15
x^25 = 705     (mod 8051)    Found Repeat:  705 at i = 10 and j = 25. Range: 15
x^26 = 5915    (mod 8051)    Found Repeat: 5915 at i = 11 and j = 26. Range: 15
x^27 = 5631    (mod 8051)    Found Repeat: 5631 at i = 12 and j = 27. Range: 15
x^28 = 3324    (mod 8051)    Found Repeat: 3324 at i = 13 and j = 28. Range: 15
x^29 = 3005    (mod 8051)    Found Repeat: 3005 at i = 14 and j = 29. Range: 15
x^30 = 4855    (mod 8051)    Found Repeat: 4855 at i = 15 and j = 30. Range: 15
x^31 = 5749    (mod 8051)    Found Repeat: 5749 at i = 16 and j = 31. Range: 15
x^32 = 1647    (mod 8051)    Found Repeat: 1647 at i = 17 and j = 32. Range: 15
x^33 = 7474    (mod 8051)    Found Repeat: 7474 at i = 18 and j = 33. Range: 15
x^34 = 2839    (mod 8051)    Found Repeat: 2839 at i = 19 and j = 34. Range: 15
x^35 = 871     (mod 8051)    Found Repeat:  871 at i = 20 and j = 35. Range: 15
x^36 = 1848    (mod 8051)    Found Repeat: 1848 at i = 21 and j = 36. Range: 15
x^37 = 1481    (mod 8051)    Found Repeat: 1481 at i = 22 and j = 37. Range: 15
x^38 = 3490    (mod 8051)    Found Repeat: 3490 at i = 23 and j = 38. Range: 15
x^39 = 6989    (mod 8051)    Found Repeat: 6989 at i = 24 and j = 39. Range: 15
x^40 = 705     (mod 8051)    Found Repeat:  705 at i = 25 and j = 40. Range: 15
x^41 = 5915    (mod 8051)    Found Repeat: 5915 at i = 26 and j = 41. Range: 15
x^42 = 5631    (mod 8051)    Found Repeat: 5631 at i = 27 and j = 42. Range: 15
x^43 = 3324    (mod 8051)    Found Repeat: 3324 at i = 28 and j = 43. Range: 15
x^44 = 3005    (mod 8051)    Found Repeat: 3005 at i = 29 and j = 44. Range: 15
x^45 = 4855    (mod 8051)    Found Repeat: 4855 at i = 30 and j = 45. Range: 15
x^46 = 5749    (mod 8051)    Found Repeat: 5749 at i = 31 and j = 46. Range: 15
x^47 = 1647    (mod 8051)    Found Repeat: 1647 at i = 32 and j = 47. Range: 15
x^48 = 7474    (mod 8051)    Found Repeat: 7474 at i = 33 and j = 48. Range: 15
x^49 = 2839    (mod 8051)    Found Repeat: 2839 at i = 34 and j = 49. Range: 15
x^50 = 871     (mod 8051)    Found Repeat:  871 at i = 35 and j = 50. Range: 15
x^51 = 1848    (mod 8051)    Found Repeat: 1848 at i = 36 and j = 51. Range: 15
x^52 = 1481    (mod 8051)    Found Repeat: 1481 at i = 37 and j = 52. Range: 15
x^53 = 3490    (mod 8051)    Found Repeat: 3490 at i = 38 and j = 53. Range: 15
x^54 = 6989    (mod 8051)    Found Repeat: 6989 at i = 39 and j = 54. Range: 15
x^55 = 705     (mod 8051)    Found Repeat:  705 at i = 40 and j = 55. Range: 15
x^56 = 5915    (mod 8051)    Found Repeat: 5915 at i = 41 and j = 56. Range: 15
x^57 = 5631    (mod 8051)    Found Repeat: 5631 at i = 42 and j = 57. Range: 15
x^58 = 3324    (mod 8051)    Found Repeat: 3324 at i = 43 and j = 58. Range: 15
x^59 = 3005    (mod 8051)    Found Repeat: 3005 at i = 44 and j = 59. Range: 15
x^60 = 4855    (mod 8051)    Found Repeat: 4855 at i = 45 and j = 60. Range: 15
x^61 = 5749    (mod 8051)    Found Repeat: 5749 at i = 46 and j = 61. Range: 15
x^62 = 1647    (mod 8051)    Found Repeat: 1647 at i = 47 and j = 62. Range: 15
x^63 = 7474    (mod 8051)    Found Repeat: 7474 at i = 48 and j = 63. Range: 15
x^64 = 2839    (mod 8051)    Found Repeat: 2839 at i = 49 and j = 64. Range: 15
x^65 = 871     (mod 8051)    Found Repeat:  871 at i = 50 and j = 65. Range: 15
x^66 = 1848    (mod 8051)    Found Repeat: 1848 at i = 51 and j = 66. Range: 15
x^67 = 1481    (mod 8051)    Found Repeat: 1481 at i = 52 and j = 67. Range: 15
x^68 = 3490    (mod 8051)    Found Repeat: 3490 at i = 53 and j = 68. Range: 15
x^69 = 6989    (mod 8051)    Found Repeat: 6989 at i = 54 and j = 69. Range: 15
"""